from __future__ import annotations

from pathlib import Path

from export_data import main as export_main


ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs"
INDEX_HTML = DOCS_DIR / "index.html"
STYLE_CSS = DOCS_DIR / "style.css"


HTML = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>LLM YouTube Landscape Tracker</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <header class="site-header">
    <div>
      <h1>LLM YouTube Landscape Tracker</h1>
      <p>自动追踪 YouTube 上的 AI、LLM、Agent、RAG、基础设施和产品趋势。</p>
      <p><a href="table.html" class="table-link">Open concise table</a></p>
    </div>
  </header>

  <main>
    <section class="stats" id="stats"></section>

    <section class="controls">
      <input id="search" type="search" placeholder="搜索标题、频道、公司、模型、主题..." />
      <select id="importance">
        <option value="">全部重要性</option>
        <option value="high">high</option>
        <option value="medium">medium</option>
        <option value="low">low</option>
      </select>
      <select id="topic">
        <option value="">全部主题</option>
      </select>
    </section>

    <section id="cards" class="cards"></section>
  </main>

  <footer>
    <p>Generated by Poe API + GitHub Pages.</p>
  </footer>

  <script>
    let allItems = [];
    let allTopics = [];

    function textOf(value) {
      if (value === null || value === undefined) return "";
      if (Array.isArray(value)) return value.join(" ");
      if (typeof value === "object") return JSON.stringify(value);
      return String(value);
    }

    function escapeHtml(str) {
      return String(str || "")
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;")
        .replaceAll('"', "&quot;")
        .replaceAll("'", "&#039;");
    }

    function renderStats(payload) {
      const stats = payload.stats || {};
      const el = document.getElementById("stats");

      const topTopics = (stats.topics || []).slice(0, 8)
        .map(([name, count]) => `<span class="pill">${escapeHtml(name)} ${count}</span>`)
        .join("");

      el.innerHTML = `
        <div class="stat"><strong>${stats.total_videos || 0}</strong><span>Total Videos</span></div>
        <div class="stat"><strong>${stats.analyzed_videos || 0}</strong><span>Analyzed</span></div>
        <div class="stat wide"><strong>Top Topics</strong><div class="pill-row">${topTopics}</div></div>
      `;
    }

    function buildTopicOptions(items) {
      const set = new Set();

      for (const item of items) {
        const analysis = item.analysis || {};
        const topics = analysis.topics || [];

        for (const topic of topics) {
          set.add(topic);
        }
      }

      allTopics = Array.from(set).sort();

      const select = document.getElementById("topic");

      for (const topic of allTopics) {
        const option = document.createElement("option");
        option.value = topic;
        option.textContent = topic;
        select.appendChild(option);
      }
    }

    function getSearchBlob(item) {
      const analysis = item.analysis || {};

      return [
        item.title,
        item.channel,
        item.channel_category,
        analysis.one_sentence_summary,
        analysis.detailed_summary,
        analysis.topics,
        analysis.signals,
        analysis.companies_or_projects,
        analysis.models_or_tools,
        analysis.people,
        analysis.market_impact,
        analysis.technical_takeaways,
        analysis.product_takeaways,
      ].map(textOf).join(" ").toLowerCase();
    }

    function applyFilters() {
      const q = document.getElementById("search").value.trim().toLowerCase();
      const importance = document.getElementById("importance").value;
      const topic = document.getElementById("topic").value;

      let items = allItems.slice();

      if (q) {
        items = items.filter(item => getSearchBlob(item).includes(q));
      }

      if (importance) {
        items = items.filter(item => {
          const analysis = item.analysis || {};
          return analysis.importance === importance;
        });
      }

      if (topic) {
        items = items.filter(item => {
          const analysis = item.analysis || {};
          return (analysis.topics || []).includes(topic);
        });
      }

      renderCards(items);
    }

    function renderCards(items) {
      const el = document.getElementById("cards");

      if (!items.length) {
        el.innerHTML = `<p class="empty">没有匹配的视频。</p>`;
        return;
      }

      el.innerHTML = items.map(item => {
        const a = item.analysis || {};
        const isAnalyzed = item.analysis_status === "ok" && item.analysis && typeof item.analysis === "object";
        const signals = (a.signals || []).map(t => `<span class="pill signal">${escapeHtml(t)}</span>`).join("");
        const topics = isAnalyzed ? (a.topics || []) : ["pending transcript analysis"];
        const importance = isAnalyzed ? (a.importance || "analyzed") : "unanalyzed";
        const score = isAnalyzed ? (a.watch_priority_score || a.priority || "") : "";
        const summary = isAnalyzed
        ? (a.one_sentence_summary || a.detailed_summary || "Transcript-based analysis available.")
        : "No transcript-based analysis available yet. Captions may be unavailable or this video may be pending analysis.";

        return `
          <article class="card">
            <div class="card-top">
              <div>
                <h2><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">${escapeHtml(item.title)}</a></h2>
                <p class="meta">${escapeHtml(item.channel || "")} · ${escapeHtml(item.published || "")}</p>
              </div>
              <div class="score">
                <strong>${escapeHtml(score)}</strong>
                <span>${escapeHtml(importance)}</span>
              </div>
            </div>

            <p class="summary">${escapeHtml(summary)}</p>

            ${a.importance_reason ? `<p class="reason">${escapeHtml(a.importance_reason)}</p>` : ""}

            <div class="pill-row">${topics}${signals}</div>

            ${a.market_impact ? `<h3>Market Impact</h3><p>${escapeHtml(a.market_impact)}</p>` : ""}

            ${Array.isArray(a.technical_takeaways) && a.technical_takeaways.length ? `
              <h3>Technical Takeaways</h3>
              <ul>${a.technical_takeaways.map(x => `<li>${escapeHtml(x)}</li>`).join("")}</ul>
            ` : ""}

            ${Array.isArray(a.product_takeaways) && a.product_takeaways.length ? `
              <h3>Product Takeaways</h3>
              <ul>${a.product_takeaways.map(x => `<li>${escapeHtml(x)}</li>`).join("")}</ul>
            ` : ""}
          </article>
        `;
      }).join("");
    }

    async function main() {
      const res = await fetch("data.json");
      const payload = await res.json();

      allItems = payload.items || [];

      renderStats(payload);
      buildTopicOptions(allItems);
      renderCards(allItems);

      document.getElementById("search").addEventListener("input", applyFilters);
      document.getElementById("importance").addEventListener("change", applyFilters);
      document.getElementById("topic").addEventListener("change", applyFilters);
    }

    main().catch(err => {
      document.body.innerHTML = `<pre>${escapeHtml(err.stack || err.message || err)}</pre>`;
    });
  </script>
</body>
</html>
"""


CSS = """
:root {
  color-scheme: light;
  --bg: #f6f7fb;
  --card: #ffffff;
  --text: #172033;
  --muted: #687085;
  --border: #dde2ee;
  --accent: #3867ff;
  --accent-soft: #e8edff;
  --signal: #0f8b6f;
  --signal-soft: #e1f6f0;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--text);
}

.site-header {
  padding: 48px 24px;
  background: linear-gradient(135deg, #16213e, #3867ff);
  color: white;
}

.site-header h1 {
  margin: 0 0 10px;
  font-size: clamp(30px, 5vw, 56px);
}

.site-header p {
  margin: 0;
  color: rgba(255,255,255,0.84);
  font-size: 18px;
}

main {
  max-width: 1180px;
  margin: 0 auto;
  padding: 24px;
}

.stats {
  display: grid;
  grid-template-columns: 180px 180px 1fr;
  gap: 16px;
  margin-top: -48px;
  margin-bottom: 24px;
}

.stat {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 18px;
  padding: 20px;
  box-shadow: 0 10px 30px rgba(25, 34, 70, 0.08);
}

.stat strong {
  display: block;
  font-size: 28px;
}

.stat span {
  color: var(--muted);
}

.stat.wide strong {
  font-size: 18px;
  margin-bottom: 12px;
}

.controls {
  display: grid;
  grid-template-columns: 1fr 180px 220px;
  gap: 12px;
  margin-bottom: 24px;
}

input,
select {
  width: 100%;
  border: 1px solid var(--border);
  border-radius: 14px;
  padding: 14px 16px;
  background: white;
  color: var(--text);
  font-size: 15px;
}

.cards {
  display: grid;
  gap: 18px;
}

.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 20px;
  padding: 22px;
  box-shadow: 0 10px 30px rgba(25, 34, 70, 0.05);
}

.card-top {
  display: flex;
  justify-content: space-between;
  gap: 20px;
}

.card h2 {
  margin: 0 0 8px;
  font-size: 22px;
}

.card h2 a {
  color: var(--text);
  text-decoration: none;
}

.card h2 a:hover {
  color: var(--accent);
}

.meta {
  margin: 0;
  color: var(--muted);
}

.summary {
  font-size: 17px;
  line-height: 1.6;
}

.reason {
  color: var(--muted);
  line-height: 1.6;
}

.score {
  min-width: 74px;
  height: 74px;
  border-radius: 18px;
  background: var(--accent-soft);
  color: var(--accent);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.score strong {
  font-size: 26px;
}

.score span {
  font-size: 12px;
}

.pill-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.pill {
  display: inline-flex;
  align-items: center;
  border-radius: 999px;
  padding: 6px 10px;
  background: var(--accent-soft);
  color: var(--accent);
  font-size: 13px;
}

.pill.signal {
  background: var(--signal-soft);
  color: var(--signal);
}

.card h3 {
  margin-top: 20px;
  margin-bottom: 8px;
}

.card li {
  margin: 6px 0;
  line-height: 1.5;
}

.empty {
  color: var(--muted);
}

footer {
  max-width: 1180px;
  margin: 0 auto;
  padding: 24px;
  color: var(--muted);
}

@media (max-width: 800px) {
  .stats,
  .controls {
    grid-template-columns: 1fr;
  }

  .card-top {
    flex-direction: column;
  }

  .score {
    width: 74px;
  }
}
"""


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    export_main()

    INDEX_HTML.write_text(HTML, encoding="utf-8")
    STYLE_CSS.write_text(CSS, encoding="utf-8")

    print(f"Wrote {INDEX_HTML}")
    print(f"Wrote {STYLE_CSS}")


if __name__ == "__main__":
    main()